# Accidentes de caro en Estados Unidos

### Importar paqueterias

In [1]:
import pandas as pd

### Importar los datos

In [2]:
car_accidents = pd.read_csv("US_Accidents_March23.csv", parse_dates=["Start_Time", "End_Time", "Weather_Timestamp"])

## Limpieza de datos

### Revisión de las columnas

In [3]:
pd.set_option("display.max_columns", None)

car_accidents.head(5)

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,Dayton,Montgomery,OH,45424,US,US/Eastern,KFFO,2016-02-08 05:58:00,36.9,NaN,91.0,29.68,10.0,Calm,NaN,0.02,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,Reynoldsburg,Franklin,OH,43068-3402,US,US/Eastern,KCMH,2016-02-08 05:51:00,37.9,NaN,100.0,29.65,10.0,Calm,NaN,0.00,Light Rain,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,Williamsburg,Clermont,OH,45176,US,US/Eastern,KI69,2016-02-08 06:56:00,36.0,33.3,100.0,29.67,10.0,SW,3.5,NaN,Overcast,False,False,False,False,False,False,False,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,Dayton,Montgomery,OH,45417,US,US/Eastern,KDAY,2016-02-08 07:38:00,35.1,31.0,96.0,29.64,9.0,SW,4.6,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,Dayton,Montgomery,OH,45459,US,US/Eastern,KMGY,2016-02-08 07:53:00,36.0,33.3,89.0,29.65,6.0,SW,3.5,NaN,Mostly Cloudy,False,False,False,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day

### Revision de los tipos de datos

In [4]:
car_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      datetime64[ns]
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), datetime64[ns](1), float64(12), int64(1), object(19)
memory usage: 2.0+ GB

Eliminar la columna country ya que solo tiene un valor no importa información

In [5]:
del(car_accidents["Country"])

Cambiar los tipos de datos para el analisis

In [6]:
car_accidents["Start_Time"] = pd.to_datetime(car_accidents["Start_Time"], errors="coerce")

In [7]:
car_accidents["End_Time"] = pd.to_datetime(car_accidents["End_Time"], errors="coerce")

In [8]:
car_accidents["Start_Time"].dtype

dtype('<M8[ns]')

In [9]:
car_accidents["End_Time"].dtype

dtype('<M8[ns]')

Convertir en tipo categoria las columnas con pocos datos diferentes

In [10]:
car_accidents["Sunrise_Sunset"].unique()

array(['Night', 'Day', nan], dtype=object)

In [11]:
car_accidents["Civil_Twilight"] = car_accidents["Civil_Twilight"].astype("category")

In [12]:
car_accidents["Astronomical_Twilight"] = car_accidents["Astronomical_Twilight"].astype("category")

In [13]:
car_accidents["Nautical_Twilight"] = car_accidents["Nautical_Twilight"].astype("category")

In [14]:
car_accidents["Timezone"] = car_accidents["Timezone"].astype("category")

In [15]:
car_accidents["Sunrise_Sunset"] = car_accidents["Sunrise_Sunset"].astype("category")

In [16]:
car_accidents["Wind_Direction"] = car_accidents["Wind_Direction"].astype("category")

In [17]:
car_accidents["State"] = car_accidents["State"].astype("category")

In [18]:
car_accidents["City"] = car_accidents["City"].astype("category")

In [19]:
car_accidents["County"] = car_accidents["County"].astype("category")

In [20]:
car_accidents["Airport_Code"] = car_accidents["Airport_Code"].astype("category")

Verificaciòn de tipos de datos

In [21]:
car_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 45 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   category
 13  County                 category
 14  State                  category
 15  Zipcode                object
 16  Timezone               category
 17  Airport_Code           category
 18  Weather_Timestamp      datetime64[ns]
 19  Temperature(F)         float64
 20  Wind_Chill(F)          float64
 21  Humidity(%)            float64
 22  Pressure(in)           float64
 23  Visibility(mi)         float64
 24  Wind_Direction         category
 25  Wind_Speed(mph)        float64
 26  Precipitation(in)      float64
 27  Weather_Condition      object
 28  Amenity                bool
 29  Bump                   bool
 30  Crossing               bool
 31  Give_Way               bool
 32  Junction               bool
 33  No_Exit                bool
 34  Railway                bool
 35  Roundabout             bool
 36  Station                bool
 37  Stop                   bool
 38  Traffic_Calming        bool
 39  Traffic_Signal         bool
 40  Turning_Loop           bool
 41  Sunrise_Sunset         category
 42  Civil_Twilight         category
 43  Nautical_Twilight      category
 44  Astronomical_Twilight  category
dtypes: bool(13), category(10), datetime64[ns](3), float64(12), int64(1), object(6)
memory usage: 1.5+ GB

### Revisión de duplicados

In [22]:
car_accidents.duplicated().sum()

np.int64(0)

In [23]:
car_accidents[car_accidents.duplicated()]

Empty DataFrame
Columns: [ID, Source, Severity, Start_Time, End_Time, Start_Lat, Start_Lng, End_Lat, End_Lng, Distance(mi), Description, Street, City, County, State, Zipcode, Timezone, Airport_Code, Weather_Timestamp, Temperature(F), Wind_Chill(F), Humidity(%), Pressure(in), Visibility(mi), Wind_Direction, Wind_Speed(mph), Precipitation(in), Weather_Condition, Amenity, Bump, Crossing, Give_Way, Junction, No_Exit, Railway, Roundabout, Station, Stop, Traffic_Calming, Traffic_Signal, Turning_Loop, Sunrise_Sunset, Civil_Twilight, Nautical_Twilight, Astronomical_Twilight]
Index: []

In [24]:
car_accidents[car_accidents["ID"].duplicated()]

Empty DataFrame
Columns: [ID, Source, Severity, Start_Time, End_Time, Start_Lat, Start_Lng, End_Lat, End_Lng, Distance(mi), Description, Street, City, County, State, Zipcode, Timezone, Airport_Code, Weather_Timestamp, Temperature(F), Wind_Chill(F), Humidity(%), Pressure(in), Visibility(mi), Wind_Direction, Wind_Speed(mph), Precipitation(in), Weather_Condition, Amenity, Bump, Crossing, Give_Way, Junction, No_Exit, Railway, Roundabout, Station, Stop, Traffic_Calming, Traffic_Signal, Turning_Loop, Sunrise_Sunset, Civil_Twilight, Nautical_Twilight, Astronomical_Twilight]
Index: []

### Revisión de valores faltantes

In [25]:
car_accidents.isna().sum()

ID                             0
Source                         0
Severity                       0
Start_Time                743166
End_Time                  743166
Start_Lat                      0
Start_Lng                      0
End_Lat                  3402762
End_Lng                  3402762
Distance(mi)                   0
Description                    5
Street                     10869
City                         253
County                         0
State                          0
Zipcode                     1915
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             23246
Civil_Twilight             23246
Nautical_Twilight          23246
Astronomical_Twilight      23246
dtype: int64

In [26]:
car_accidents.isna().mean() * 100

ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                9.616047
End_Time                  9.616047
Start_Lat                 0.000000
Start_Lng                 0.000000
End_Lat                  44.029355
End_Lng                  44.029355
Distance(mi)              0.000000
Description               0.000065
Street                    0.140637
City                      0.003274
County                    0.000000
State                     0.000000
Zipcode                   0.024779
Timezone                  0.101030
Airport_Code              0.292881
Weather_Timestamp         1.555666
Temperature(F)            2.120143
Wind_Chill(F)            25.865904
Humidity(%)               2.253301
Pressure(in)              1.820288
Visibility(mi)            2.291524
Wind_Direction            2.267043
Wind_Speed(mph)           7.391355
Precipitation(in)        28.512858
Weather_Condition         2.244438
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.300787
Civil_Twilight            0.300787
Nautical_Twilight         0.300787
Astronomical_Twilight     0.300787
dtype: float64

LLenar valores faltantes de la columna zipcode

In [27]:
zipcode_city = (
    car_accidents
    .dropna(subset=["Zipcode", "City"])
    .groupby("Zipcode", observed=True)["City"]
    .nunique()
)

In [28]:
zipcode_city.value_counts()

City
1    822860
2      2198
3        34
4         1
Name: count, dtype: int64

In [29]:
zipcode_to_city = (
    car_accidents
    .dropna(subset=["Zipcode", "City"])
    .groupby("Zipcode", observed=True)["City"]
    .agg(lambda x: x.iloc[0] if x.nunique() == 1 else None)
)

In [30]:
missing_city = car_accidents["City"].isna()

city_from_zip = car_accidents.loc[missing_city, "Zipcode"].map(zipcode_to_city)

city_from_zip.notna().sum()

np.int64(61)

In [31]:
car_accidents.loc[missing_city, "City"] = city_from_zip

In [32]:
car_accidents["City"].isna().sum()

np.int64(192)

LLenar espacios en blanco de la columna city

In [33]:
car_accidents.loc[
    car_accidents["City"].isna(),
    ["Zipcode", "County", "State"]
]

        Zipcode                County State
85968     92372           Los Angeles    CA
111080    92372           Los Angeles    CA
119772    34202              Sarasota    FL
122929    34202              Sarasota    FL
123702    34202              Sarasota    FL
...         ...                   ...   ...
7402216   20743  District of Columbia    DC
7463859   20745  District of Columbia    DC
7464599   20912  District of Columbia    DC
7597826   20912  District of Columbia    DC
7614480   63565             Appanoose    IA

[192 rows x 3 columns]

In [34]:
car_accidents.loc[
    missing_city & city_from_zip.notna(),
    ["City", "Zipcode", "County", "State"]
]

                     City Zipcode       County State
444980       South Beloit   61080         Rock    WI
938747   Colorado Springs   80908      Douglas    CO
1012975        Homer Glen   60491         Cook    IL
1442362          Lakeland   33809        Pasco    FL
3264349      South Beloit   61080         Rock    WI
...                   ...     ...          ...   ...
7542121         Greenwich   06831  Westchester    NY
7591970      Lake Village   46349     Kankakee    IL
7606562         Greenwich   06831  Westchester    NY
7619724         Greenwich   06831  Westchester    NY
7629988           Antwerp   45813        Allen    IN

[61 rows x 4 columns]

In [35]:
car_accidents.loc[
    missing_city & city_from_zip.notna(),
    "City"
] = city_from_zip[city_from_zip.notna()]

In [36]:
car_accidents["City"].isna().sum()

np.int64(192)

In [37]:
car_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 45 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   category
 13  County                 category
 14  State                  category
 15  Zipcode                object
 16  Timezone               category
 17  Airport_Code           category
 18  Weather_Timestamp      datetime64[ns]
 19  Temperature(F)         float64
 20  Wind_Chill(F)          float64
 21  Humidity(%)            float64
 22  Pressure(in)           float64
 23  Visibility(mi)         float64
 24  Wind_Direction         category
 25  Wind_Speed(mph)        float64
 26  Precipitation(in)      float64
 27  Weather_Condition      object
 28  Amenity                bool
 29  Bump                   bool
 30  Crossing               bool
 31  Give_Way               bool
 32  Junction               bool
 33  No_Exit                bool
 34  Railway                bool
 35  Roundabout             bool
 36  Station                bool
 37  Stop                   bool
 38  Traffic_Calming        bool
 39  Traffic_Signal         bool
 40  Turning_Loop           bool
 41  Sunrise_Sunset         category
 42  Civil_Twilight         category
 43  Nautical_Twilight      category
 44  Astronomical_Twilight  category
dtypes: bool(13), category(10), datetime64[ns](3), float64(12), int64(1), object(6)
memory usage: 1.5+ GB

llenar datos faltantes de la columna timezone

In [38]:
state_city = (
    car_accidents
    .dropna(subset=['State', 'City', 'Timezone'])
    .groupby(['State', 'City'], observed=True)['Timezone']
    .nunique()
)

state_city.value_counts()

Timezone
1    20269
2        6
Name: count, dtype: int64

In [39]:
timezone_state_city = (
    car_accidents
    .dropna(subset=['State', 'City', 'Timezone'])
    .groupby(['State', 'City'], observed=True)['Timezone']
    .nunique()
)

timezone_state_city = timezone_state_city[timezone_state_city == 1]

In [40]:
timezone_map = (
    car_accidents
    .dropna(subset=['State', 'City', 'Timezone'])
    .groupby(['State', 'City'], observed=True)['Timezone']
    .first()
)

In [41]:
timezone_from_city = (
    car_accidents.set_index(['State', 'City'])
    .index
    .map(timezone_map)
)

missing = car_accidents['Timezone'].isna()

print("Timezone faltantes:", missing.sum())
print("Se pueden recuperar:", timezone_from_city[missing].notna().sum())
print("No se pueden recuperar:", timezone_from_city[missing].isna().sum())

Timezone faltantes: 7808
Se pueden recuperar: 6256
No se pueden recuperar: 1552

In [42]:
car_accidents.loc[missing, 'Timezone'] = timezone_from_city[missing]

In [43]:
timezone_from_city = (
    car_accidents.set_index(['State', 'City']).index
    .map(timezone_map)
)

timezone_from_city = pd.Series(
    timezone_from_city,
    index=car_accidents.index
)

car_accidents['Timezone'] = car_accidents['Timezone'].fillna(
    timezone_from_city
)

In [44]:
car_accidents['Timezone'].isna().sum()

np.int64(1552)

llenar datos faltantes de la columna city

In [45]:
state_county_zip_city = (
    car_accidents
    .dropna(subset=['State', 'County', 'Zipcode', 'City'])
    .groupby(
        ['State', 'County', 'Zipcode'],
        observed=True
    )['City']
    .nunique()
)

state_county_zip_city.value_counts()

City
1    830673
2      2085
3        16
4         1
Name: count, dtype: int64

In [46]:
city_count = (
    car_accidents
    .dropna(subset=['State', 'County', 'Zipcode', 'City'])
    .groupby(
        ['State', 'County', 'Zipcode'],
        observed=True
    )['City']
    .nunique()
)

valid_combinations = city_count[city_count == 1].index

city_map = (
    car_accidents
    .dropna(subset=['State', 'County', 'Zipcode', 'City'])
    .drop_duplicates(['State', 'County', 'Zipcode'])
    .set_index(['State', 'County', 'Zipcode'])['City']
)

city_from_location = (
    car_accidents.set_index(
        ['State', 'County', 'Zipcode']
    ).index.map(city_map)
)

city_from_location = pd.Series(
    city_from_location,
    index=car_accidents.index
)

missing_city = car_accidents['City'].isna()

print("City faltantes:", missing_city.sum())
print(
    "Se pueden recuperar:",
    city_from_location[missing_city].notna().sum()
)
print(
    "No se pueden recuperar:",
    city_from_location[missing_city].isna().sum()
)

City faltantes: 192
Se pueden recuperar: 33
No se pueden recuperar: 159

In [47]:
car_accidents['City'] = car_accidents['City'].fillna(city_from_location)

In [48]:
car_accidents['City'].isna().sum()

np.int64(159)

zipcode y street no se pudo llenar ninguno con seguridad

### Revisar inconsistencias

In [49]:
car_accidents[['Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng']].describe()

          Start_Lat     Start_Lng       End_Lat       End_Lng
count  7.728394e+06  7.728394e+06  4.325632e+06  4.325632e+06
mean   3.620119e+01 -9.470255e+01  3.626183e+01 -9.572557e+01
std    5.076079e+00  1.739176e+01  5.272905e+00  1.810793e+01
min    2.455480e+01 -1.246238e+02  2.456601e+01 -1.245457e+02
25%    3.339963e+01 -1.172194e+02  3.346207e+01 -1.177543e+02
50%    3.582397e+01 -8.776662e+01  3.618349e+01 -8.802789e+01
75%    4.008496e+01 -8.035368e+01  4.017892e+01 -8.024709e+01
max    4.900220e+01 -6.711317e+01  4.907500e+01 -6.710924e+01

Normalizacion de datos de columna city

In [50]:
city_normalized = (
    car_accidents['City']
    .dropna()
    .str.strip()
    .str.lower()
)

city_variants = (
    pd.DataFrame({
        'original': car_accidents.loc[city_normalized.index, 'City'],
        'normalized': city_normalized
    })
    .groupby('normalized')['original']
    .nunique()
    .sort_values(ascending=False)
)

city_variants[city_variants > 1]

normalized
cardiff by the sea        3
mccleary                  2
mcarthur                  2
marina del rey            2
mccall                    2
marine on saint croix     2
fond du lac               2
mccammon                  2
mclean                    2
la place                  2
mccloud                   2
forks of salmon           2
isle of palms             2
meadows of dan            2
mcconnelsville            2
mccordsville              2
mcclellan                 2
prairie du chien          2
havre de grace            2
prairie du sac            2
township of washington    2
mcallen                   2
debary                    2
playa del rey             2
lagrange                  2
ponce de leon             2
croton on hudson          2
bird in hand              2
dewitt                    2
west des moines           2
mi wuk village            2
travis afb                2
charleston afb            2
hastings on hudson        2
mccomb                    2
bayou la batre            2
howey in the hills        2
mckeesport                2
mchenry                   2
mcgregor                  2
castleton on hudson       2
point of rocks            2
mckinleyville             2
corona del mar            2
mckinney                  2
shaw afb                  2
mouth of wilson           2
rough and ready           2
mcloud                    2
mcminnville               2
lake in the hills         2
deland                    2
king of prussia           2
sheppard afb              2
mcdonough                 2
Name: original, dtype: int64

In [51]:
city_normalized = car_accidents['City'].str.strip().str.casefold()

city_variants = (
    pd.DataFrame({
        'City_original': car_accidents['City'],
        'City_normalized': city_normalized
    })
    .dropna()
    .groupby('City_normalized')['City_original']
    .unique()
)

city_variants = city_variants[city_variants.apply(len) > 1]

city_variants

City_normalized
bayou la batre            ['Bayou La Batre', 'Bayou la Batre']
Categorie...
bird in hand              ['Bird In Hand', 'Bird in Hand']
Categories (1...
cardiff by the sea        ['Cardiff By the Sea', 'Cardiff by the Sea', '...
castleton on hudson       ['Castleton On Hudson', 'Castleton on Hudson']...
charleston afb            ['Charleston Afb', 'Charleston AFB']
Categorie...
corona del mar            ['Corona del Mar', 'Corona Del Mar']
Categorie...
croton on hudson          ['Croton on Hudson', 'Croton On Hudson']
Categ...
debary                    ['Debary', 'DeBary']
Categories (13678, object...
deland                    ['Deland', 'DeLand']
Categories (13678, object...
dewitt                    ['DeWitt', 'Dewitt']
Categories (13678, object...
fond du lac               ['Fond du Lac', 'Fond Du Lac']
Categories (136...
forks of salmon           ['Forks of Salmon', 'Forks Of Salmon']
Categor...
hastings on hudson        ['Hastings On Hudson', 'Hastings on Hudson']
C...
havre de grace            ['Havre de Grace', 'Havre De Grace']
Categorie...
howey in the hills        ['Howey in the Hills', 'Howey In The Hills']
C...
isle of palms             ['Isle of Palms', 'Isle Of Palms']
Categories ...
king of prussia           ['King Of Prussia', 'King of Prussia']
Categor...
la place                  ['LA Place', 'La Place']
Categories (13678, ob...
lagrange                  ['LaGrange', 'Lagrange']
Categories (13678, ob...
lake in the hills         ['Lake in the Hills', 'Lake In The Hills']
Cat...
marina del rey            ['Marina Del Rey', 'Marina del Rey']
Categorie...
marine on saint croix     ['Marine On Saint Croix', 'Marine on Saint Cro...
mcallen                   ['McAllen', 'Mcallen']
Categories (13678, obje...
mcarthur                  ['McArthur', 'Mcarthur']
Categories (13678, ob...
mccall                    ['Mccall', 'McCall']
Categories (13678, object...
mccammon                  ['Mccammon', 'McCammon']
Categories (13678, ob...
mccleary                  ['McCleary', 'Mccleary']
Categories (13678, ob...
mcclellan                 ['McClellan', 'Mcclellan']
Categories (13678, ...
mccloud                   ['McCloud', 'Mccloud']
Categories (13678, obje...
mccomb                    ['McComb', 'Mccomb']
Categories (13678, object...
mcconnelsville            ['Mcconnelsville', 'McConnelsville']
Categorie...
mccordsville              ['McCordsville', 'Mccordsville']
Categories (1...
mcdonough                 ['McDonough', 'Mcdonough']
Categories (13678, ...
mcgregor                  ['McGregor', 'Mcgregor']
Categories (13678, ob...
mchenry                   ['McHenry', 'Mchenry']
Categories (13678, obje...
mckeesport                ['Mckeesport', 'McKeesport']
Categories (13678...
mckinleyville             ['McKinleyville', 'Mckinleyville']
Categories ...
mckinney                  ['McKinney', 'Mckinney']
Categories (13678, ob...
mclean                    ['McLean', 'Mclean']
Categories (13678, object...
mcloud                    ['McLoud', 'Mcloud']
Categories (13678, object...
mcminnville               ['McMinnville', 'Mcminnville']
Categories (136...
meadows of dan            ['Meadows of Dan', 'Meadows Of Dan']
Categorie...
mi wuk village            ['Mi Wuk Village', 'MI Wuk Village']
Categorie...
mouth of wilson           ['Mouth Of Wilson', 'Mouth of Wilson']
Categor...
playa del rey             ['Playa del Rey', 'Playa Del Rey']
Categories ...
point of rocks            ['Point of Rocks', 'Point Of Rocks']
Categorie...
ponce de leon             ['Ponce de Leon', 'Ponce De Leon']
Categories ...
prairie du chien          ['Prairie Du Chien', 'Prairie du Chien']
Categ...
prairie du sac            ['Prairie Du Sac', 'Prairie du Sac']
Categorie...
rough and ready           ['Rough and Ready', 'Rough And Ready']
Categor...
shaw afb                  ['Shaw Afb', 'Shaw AFB']
Categories (13678, ob...
sheppard afb              ['Sheppard AFB', 'Sheppard Afb']
Categories (1...
township of washington    ['Township of Washington', 'Township Of Washin...
travis afb                ['Travis Afb', 'Travis AFB']
Categories (13678...
west des moines           ['West des Moines', 'West Des Moines']
Categor...
Name: City_original, dtype: object

In [52]:
city_counts = (
    car_accidents
    .dropna(subset=['City'])
    .assign(
        City_normalized=lambda x: x['City'].str.strip().str.casefold()
    )
    .groupby(['City_normalized', 'City'], observed=True)
    .size()
)

In [53]:
for city in city_variants.index:
    print(f"\n{city}")
    
    mask = city_normalized == city
    
    print(
        car_accidents.loc[mask, 'City']
        .value_counts()
    )

bayou la batre
City
Bayou La Batre    4
Bayou la Batre    1
Oswego            0
Osyka             0
Otego             0
                 ..
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Glen Cove         0
Zwingle           0
Name: count, Length: 13678, dtype: int64

bird in hand
City
Bird In Hand     88
Bird in Hand     52
Aaronsburg        0
Oswayo            0
Oswegatchie       0
                 ..
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Glen Cove         0
Zwingle           0
Name: count, Length: 13678, dtype: int64

cardiff by the sea
City
Cardiff By the Sea    940
Cardiff By The Sea    134
Cardiff by the Sea     97
Aaronsburg              0
Otwell                  0
                     ...
Glen Campbell           0
Glen Carbon             0
Glen Cove               0
Glen Daniel             0
Zwingle                 0
Name: count, Length: 13678, dtype: int64

castleton on hudson
City
Castleton on Hudson    342
Castleton On Hudson    108
Aaronsburg               0
Oswayo                   0
Oswego                   0
                      ...
Glen Burnie              0
Glen Campbell            0
Glen Carbon              0
Glen Cove                0
Zwingle                  0
Name: count, Length: 13678, dtype: int64

charleston afb
City
Charleston Afb    2
Charleston AFB    2
Aaronsburg        0
Otley             0
Oswayo            0
                 ..
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Glen Cove         0
Zwingle           0
Name: count, Length: 13678, dtype: int64

corona del mar
City
Corona del Mar    25
Corona Del Mar    25
Aaronsburg         0
Otsego             0
Oswegatchie        0
                  ..
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Glen Cove          0
Zwingle            0
Name: count, Length: 13678, dtype: int64

croton on hudson
City
Croton on Hudson    144
Croton On Hudson     75
Aaronsburg            0
Ottawa                0
Osyka                 0
                   ...
Glen Burnie           0
Glen Campbell         0
Glen Carbon           0
Glen Cove             0
Zwingle               0
Name: count, Length: 13678, dtype: int64

debary
City
Debary           429
DeBary            25
Otranto            0
Oswayo             0
Oswegatchie        0
                ...
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Glen Cove          0
Zwingle            0
Name: count, Length: 13678, dtype: int64

deland
City
Deland           1478
DeLand            388
Otley               0
Oswayo              0
Oswegatchie         0
                 ...
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Glen Cove           0
Zwingle             0
Name: count, Length: 13678, dtype: int64

dewitt
City
DeWitt           122
Dewitt            95
Aaronsburg         0
Otranto            0
Oswegatchie        0
                ...
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Glen Cove          0
Zwingle            0
Name: count, Length: 13678, dtype: int64

fond du lac
City
Fond du Lac      224
Fond Du Lac       21
Aaronsburg         0
Otranto            0
Oswego             0
                ...
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Glen Cove          0
Zwingle            0
Name: count, Length: 13678, dtype: int64

forks of salmon
City
Forks of Salmon    18
Forks Of Salmon     2
Aaronsburg          0
Oswayo              0
Oswego              0
                   ..
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Glen Cove           0
Zwingle             0
Name: count, Length: 13678, dtype: int64

hastings on hudson
City
Hastings on Hudson    155
Hastings On Hudson     43
Aaronsburg              0
Osterburg               0
Ostrander               0
                     ...
Glen Arm                0
Glen Aubrey             0
Glen Burnie             0
Glen Campbell           0
Zwingle                 0
Name: count, Length: 13678, dtype: int64

havre de grace
City
Havre de Grace    616
Havre De Grace    163
Aaronsburg          0
Otley               0
Oswayo              0
                 ...
Glen Arm            0
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Zwingle             0
Name: count, Length: 13678, dtype: int64

howey in the hills
City
Howey in the Hills    167
Howey In The Hills     23
Aaronsburg              0
Osteen                  0
Osterville              0
                     ...
Glen Arm                0
Glen Aubrey             0
Glen Burnie             0
Glen Campbell           0
Zwingle                 0
Name: count, Length: 13678, dtype: int64

isle of palms
City
Isle Of Palms    6
Isle of Palms    3
Otto             0
Otisco           0
Osterville       0
                ..
Glen Arm         0
Glen Aubrey      0
Glen Burnie      0
Glen Campbell    0
Zwingle          0
Name: count, Length: 13678, dtype: int64

king of prussia
City
King of Prussia    3033
King Of Prussia    1292
Aaronsburg            0
Otley                 0
Oswegatchie           0
                   ...
Glen Arm              0
Glen Aubrey           0
Glen Burnie           0
Glen Campbell         0
Zwingle               0
Name: count, Length: 13678, dtype: int64

la place
City
LA Place         476
La Place           8
Aaronsburg         0
Otisville          0
Ostrander          0
                ...
Glen Arm           0
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Zwingle            0
Name: count, Length: 13678, dtype: int64

lagrange
City
LaGrange         388
Lagrange         253
Aaronsburg         0
Otisville          0
Ostrander          0
                ...
Glen Arm           0
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Zwingle            0
Name: count, Length: 13678, dtype: int64

lake in the hills
City
Lake in the Hills    36
Lake In The Hills     5
Aaronsburg            0
Otisville             0
Ostrander             0
                     ..
Glen Arm              0
Glen Aubrey           0
Glen Burnie           0
Glen Campbell         0
Zwingle               0
Name: count, Length: 13678, dtype: int64

marina del rey
City
Marina Del Rey    487
Marina del Rey    341
Otisville           0
Ostrander           0
Oswayo              0
                 ...
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

marine on saint croix
City
Marine On Saint Croix    28
Marine on Saint Croix     5
Aaronsburg                0
Osterburg                 0
Ostrander                 0
                         ..
Glen Aubrey               0
Glen Burnie               0
Glen Campbell             0
Glen Carbon               0
Zwingle                   0
Name: count, Length: 13678, dtype: int64

mcallen
City
McAllen          26
Mcallen          15
Otley             0
Oswayo            0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mcarthur
City
McArthur         423
Mcarthur          30
Aaronsburg         0
Otley              0
Oswegatchie        0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mccall
City
Mccall           11
McCall            5
Aaronsburg        0
Otley             0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mccammon
City
McCammon         17
Mccammon          4
Aaronsburg        0
Otley             0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mccleary
City
McCleary         55
Mccleary         10
Aaronsburg        0
Otley             0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mcclellan
City
McClellan        158
Mcclellan         61
Aaronsburg         0
Otley              0
Oswegatchie        0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mccloud
City
McCloud          205
Mccloud            6
Aaronsburg         0
Oswegatchie        0
Oswego             0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mccomb
City
McComb           43
Mccomb            5
Otsego            0
Oswegatchie       0
Oswego            0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mcconnelsville
City
Mcconnelsville    10
McConnelsville     1
Aaronsburg         0
Otranto            0
Oswegatchie        0
                  ..
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mccordsville
City
Mccordsville     20
McCordsville     14
Aaronsburg        0
Otranto           0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mcdonough
City
McDonough        1552
Mcdonough          54
Otsego              0
Oswegatchie         0
Oswego              0
                 ...
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

mcgregor
City
McGregor         28
Mcgregor         19
Aaronsburg        0
Otsego            0
Oswego            0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mchenry
City
McHenry          148
Mchenry           89
Aaronsburg         0
Otsego             0
Oswego             0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mckeesport
City
McKeesport       83
Mckeesport       81
Aaronsburg        0
Otsego            0
Oswego            0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mckinleyville
City
Mckinleyville    412
McKinleyville    303
Aaronsburg         0
Otsego             0
Oswego             0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mckinney
City
McKinney         489
Mckinney          10
Otsego             0
Oswego             0
Osyka              0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mclean
City
McLean           688
Mclean             2
Oswayo             0
Oswegatchie        0
Oswego             0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mcloud
City
Mcloud           25
McLoud            5
Otsego            0
Oswego            0
Osyka             0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

mcminnville
City
Mcminnville      510
McMinnville      492
Otsego             0
Oswegatchie        0
Oswego             0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

meadows of dan
City
Meadows of Dan    25
Meadows Of Dan     7
Otsego             0
Oswego             0
Osyka              0
                  ..
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

mi wuk village
City
MI Wuk Village    103
Mi Wuk Village     33
Ostrander           0
Oswayo              0
Oswegatchie         0
                 ...
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

mouth of wilson
City
Mouth Of Wilson    12
Mouth of Wilson    10
Aaronsburg          0
Otley               0
Ostrander           0
                   ..
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

playa del rey
City
Playa del Rey    23
Playa Del Rey     6
Aaronsburg        0
Oswayo            0
Oswegatchie       0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

point of rocks
City
Point of Rocks    61
Point Of Rocks     8
Aaronsburg         0
Otisco             0
Ostrander          0
                  ..
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

ponce de leon
City
Ponce de Leon    235
Ponce De Leon     78
Aaronsburg         0
Otisco             0
Osterville         0
                ...
Glen Aubrey        0
Glen Burnie        0
Glen Campbell      0
Glen Carbon        0
Zwingle            0
Name: count, Length: 13678, dtype: int64

prairie du chien
City
Prairie du Chien    5
Prairie Du Chien    1
Aaronsburg          0
Ostrander           0
Oswayo              0
                   ..
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

prairie du sac
City
Prairie du Sac    6
Prairie Du Sac    5
Otley             0
Ostrander         0
Oswayo            0
                 ..
Glen Aubrey       0
Glen Burnie       0
Glen Campbell     0
Glen Carbon       0
Zwingle           0
Name: count, Length: 13678, dtype: int64

rough and ready
City
Rough And Ready    69
Rough and Ready    57
Aaronsburg          0
Otisco              0
Ostrander           0
                   ..
Glen Aubrey         0
Glen Burnie         0
Glen Campbell       0
Glen Carbon         0
Zwingle             0
Name: count, Length: 13678, dtype: int64

shaw afb
City
Shaw AFB         6
Shaw Afb         5
Aaronsburg       0
Otranto          0
Oswayo           0
                ..
Glen Aubrey      0
Glen Burnie      0
Glen Campbell    0
Glen Carbon      0
Zwingle          0
Name: count, Length: 13678, dtype: int64

sheppard afb
City
Sheppard AFB     5
Sheppard Afb     4
Otisville        0
Osterville       0
Ostrander        0
                ..
Glen Aubrey      0
Glen Burnie      0
Glen Campbell    0
Glen Carbon      0
Zwingle          0
Name: count, Length: 13678, dtype: int64

township of washington
City
Township of Washington    152
Township Of Washington     12
Aaronsburg                  0
Ossining                    0
Osteen                      0
                         ...
Glen Aubrey                 0
Glen Burnie                 0
Glen Campbell               0
Glen Carbon                 0
Zwingle                     0
Name: count, Length: 13678, dtype: int64

travis afb
City
Travis AFB       8
Travis Afb       1
Aaronsburg       0
Otis             0
Osterburg        0
                ..
Glen Aubrey      0
Glen Burnie      0
Glen Campbell    0
Glen Carbon      0
Zwingle          0
Name: count, Length: 13678, dtype: int64

west des moines
City
West des Moines    909
West Des Moines    209
Aaronsburg           0
Ostrander            0
Oswayo               0
                  ...
Glen Aubrey          0
Glen Burnie          0
Glen Campbell        0
Glen Carbon          0
Zwingle              0
Name: count, Length: 13678, dtype: int64

In [54]:
city_corrections = {}

for normalized, variants in city_variants.items():
    counts = (
        car_accidents.loc[
            city_normalized.eq(normalized),
            'City'
        ]
        .value_counts()
    )
    
    canonical = counts.index[0]
    
    for variant in variants:
        if variant != canonical:
            city_corrections[variant] = canonical

In [55]:
for original, corrected in city_corrections.items():
    print(f"{original} → {corrected}")

Bayou la Batre → Bayou La Batre
Bird in Hand → Bird In Hand
Cardiff by the Sea → Cardiff By the Sea
Cardiff By The Sea → Cardiff By the Sea
Castleton On Hudson → Castleton on Hudson
Charleston AFB → Charleston Afb
Corona Del Mar → Corona del Mar
Croton On Hudson → Croton on Hudson
DeBary → Debary
DeLand → Deland
Dewitt → DeWitt
Fond Du Lac → Fond du Lac
Forks Of Salmon → Forks of Salmon
Hastings On Hudson → Hastings on Hudson
Havre De Grace → Havre de Grace
Howey In The Hills → Howey in the Hills
Isle of Palms → Isle Of Palms
King Of Prussia → King of Prussia
La Place → LA Place
Lagrange → LaGrange
Lake In The Hills → Lake in the Hills
Marina del Rey → Marina Del Rey
Marine on Saint Croix → Marine On Saint Croix
Mcallen → McAllen
Mcarthur → McArthur
McCall → Mccall
Mccammon → McCammon
Mccleary → McCleary
Mcclellan → McClellan
Mccloud → McCloud
Mccomb → McComb
McConnelsville → Mcconnelsville
McCordsville → Mccordsville
Mcdonough → McDonough
Mcgregor → McGregor
Mchenry → McHenry
Mckeesport → McKeesport
McKinleyville → Mckinleyville
Mckinney → McKinney
Mclean → McLean
McLoud → Mcloud
McMinnville → Mcminnville
Meadows Of Dan → Meadows of Dan
Mi Wuk Village → MI Wuk Village
Mouth of Wilson → Mouth Of Wilson
Playa Del Rey → Playa del Rey
Point Of Rocks → Point of Rocks
Ponce De Leon → Ponce de Leon
Prairie Du Chien → Prairie du Chien
Prairie Du Sac → Prairie du Sac
Rough and Ready → Rough And Ready
Shaw Afb → Shaw AFB
Sheppard Afb → Sheppard AFB
Township Of Washington → Township of Washington
Travis Afb → Travis AFB
West Des Moines → West des Moines

In [56]:
car_accidents['City'] = car_accidents['City'].astype('string')
car_accidents['City'] = car_accidents['City'].replace(city_corrections)

comprobar

In [57]:
city_normalized = (
    car_accidents['City']
    .str.strip()
    .str.casefold()
)

In [58]:
city_check = (
    pd.DataFrame({
        'original': car_accidents['City'],
        'normalized': city_normalized
    })
    .dropna()
    .groupby('normalized')['original']
    .nunique()
)

city_check[city_check > 1]

Series([], Name: original, dtype: int64)

In [59]:
(city_check > 1).sum()

np.int64(0)

In [60]:
car_accidents['City'] = car_accidents['City'].astype('category')

Revisar columna county

In [61]:
county_normalized = (
    car_accidents['County']
    .dropna()
    .str.strip()
    .str.lower()
)

county_variants = (
    pd.DataFrame({
        'original': car_accidents.loc[county_normalized.index, 'County'],
        'normalized': county_normalized
    })
    .groupby('normalized')['original']
    .nunique()
    .sort_values(ascending=False)
)

county_variants[county_variants > 1]

normalized
mcleod                  2
mclennan                2
king and queen          2
dupage                  2
mcclain                 2
mccracken               2
lagrange                2
mcdowell                2
mcduffie                2
mchenry                 2
mcintosh                2
mckean                  2
isle of wight           2
district of columbia    2
mclean                  2
lewis and clark         2
mccormick               2
st john the baptist     2
dewitt                  2
laporte                 2
desoto                  2
dekalb                  2
fond du lac             2
mcminn                  2
Name: original, dtype: int64

In [62]:
county_normalized = car_accidents['County'].str.strip().str.casefold()

county_variants = (
    pd.DataFrame({
        'County_original': car_accidents['County'],
        'County_normalized': county_normalized
    })
    .dropna()
    .groupby('County_normalized')['County_original']
    .unique()
)

county_variants = county_variants[county_variants.apply(len) > 1]

county_variants

County_normalized
dekalb                  ['DeKalb', 'Dekalb']
Categories (1871, object)...
desoto                  ['DeSoto', 'Desoto']
Categories (1871, object)...
dewitt                  ['DeWitt', 'Dewitt']
Categories (1871, object)...
district of columbia    ['District of Columbia', 'District Of Columbia...
dupage                  ['Dupage', 'DuPage']
Categories (1871, object)...
fond du lac             ['Fond du Lac', 'Fond Du Lac']
Categories (187...
isle of wight           ['Isle of Wight', 'Isle Of Wight']
Categories ...
king and queen          ['King and Queen', 'King And Queen']
Categorie...
lagrange                ['LaGrange', 'Lagrange']
Categories (1871, obj...
laporte                 ['Laporte', 'LaPorte']
Categories (1871, objec...
lewis and clark         ['Lewis and Clark', 'Lewis And Clark']
Categor...
mcclain                 ['McClain', 'Mcclain']
Categories (1871, objec...
mccormick               ['McCormick', 'Mccormick']
Categories (1871, o...
mccracken               ['McCracken', 'Mccracken']
Categories (1871, o...
mcdowell                ['McDowell', 'Mcdowell']
Categories (1871, obj...
mcduffie                ['McDuffie', 'Mcduffie']
Categories (1871, obj...
mchenry                 ['McHenry', 'Mchenry']
Categories (1871, objec...
mcintosh                ['McIntosh', 'Mcintosh']
Categories (1871, obj...
mckean                  ['McKean', 'Mckean']
Categories (1871, object)...
mclean                  ['McLean', 'Mclean']
Categories (1871, object)...
mclennan                ['McLennan', 'Mclennan']
Categories (1871, obj...
mcleod                  ['McLeod', 'Mcleod']
Categories (1871, object)...
mcminn                  ['McMinn', 'Mcminn']
Categories (1871, object)...
st john the baptist     ['St John the Baptist', 'St John The Baptist']...
Name: County_original, dtype: object

In [63]:
county_counts = (
    car_accidents
    .dropna(subset=['County'])
    .assign(
        County_normalized=lambda x: x['County'].str.strip().str.casefold()
    )
    .groupby(['County_normalized', 'County'], observed=True)
    .size()
)

In [64]:
for county in county_variants.index:
    print(f"\n{city}")
    
    mask = county_normalized == county
    
    print(
        car_accidents.loc[mask, 'County']
        .value_counts()
    )

west des moines
County
DeKalb        22266
Dekalb         2756
Abbeville         0
Ouachita          0
Palm Beach        0
              ...
Garrett           0
Garrard           0
Garland           0
Garfield          0
Ziebach           0
Name: count, Length: 1871, dtype: int64

west des moines
County
DeSoto        1574
Desoto         198
Abbeville        0
Otter Tail       0
Page             0
              ...
Garrett          0
Garrard          0
Garland          0
Garfield         0
Ziebach          0
Name: count, Length: 1871, dtype: int64

west des moines
County
DeWitt        5
Dewitt        1
Abbeville     0
Otter Tail    0
Page          0
             ..
Garrett       0
Garrard       0
Garland       0
Garfield      0
Ziebach       0
Name: count, Length: 1871, dtype: int64

west des moines
County
District of Columbia    18302
District Of Columbia      331
Abbeville                   0
Page                        0
Pacific                     0
                        ...
Garrett                     0
Garrard                     0
Garland                     0
Garfield                    0
Ziebach                     0
Name: count, Length: 1871, dtype: int64

west des moines
County
DuPage       32447
Dupage        8592
Abbeville        0
Onslow           0
Pacific          0
             ...
Garrett          0
Garrard          0
Garland          0
Garfield         0
Ziebach          0
Name: count, Length: 1871, dtype: int64

west des moines
County
Fond du Lac    330
Fond Du Lac      6
Otter Tail       0
Page             0
Pacific          0
              ...
Garrett          0
Garrard          0
Garland          0
Garfield         0
Ziebach          0
Name: count, Length: 1871, dtype: int64

west des moines
County
Isle of Wight    876
Isle Of Wight     23
Otter Tail         0
Page               0
Pacific            0
                ...
Garland            0
Garfield           0
Galveston          0
Gallia             0
Ziebach            0
Name: count, Length: 1871, dtype: int64

west des moines
County
King and Queen    130
King And Queen      5
Ottawa              0
Pacific             0
Ozaukee             0
                 ...
Garland             0
Garfield            0
Galveston           0
Gallia              0
Ziebach             0
Name: count, Length: 1871, dtype: int64

west des moines
County
LaGrange     123
Lagrange      33
Abbeville      0
Page           0
Ozaukee        0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
LaPorte      437
Laporte      121
Ottawa         0
Pacific        0
Ozaukee        0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
Lewis and Clark    1421
Lewis And Clark       4
Abbeville             0
Ouachita              0
Page                  0
                   ...
Garland               0
Garfield              0
Galveston             0
Gallia                0
Ziebach               0
Name: count, Length: 1871, dtype: int64

west des moines
County
McClain      162
Mcclain        4
Abbeville      0
Page           0
Pacific        0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
McCormick     409
Mccormick      49
Abbeville       0
Otter Tail      0
Page            0
             ...
Garland         0
Garfield        0
Galveston       0
Gallia          0
Ziebach         0
Name: count, Length: 1871, dtype: int64

west des moines
County
McCracken     46
Mccracken      2
Abbeville      0
Otter Tail     0
Page           0
              ..
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
McDowell      849
Mcdowell        1
Abbeville       0
Otter Tail      0
Page            0
             ...
Garland         0
Garfield        0
Galveston       0
Gallia          0
Ziebach         0
Name: count, Length: 1871, dtype: int64

west des moines
County
McDuffie      234
Mcduffie        2
Abbeville       0
Otter Tail      0
Page            0
             ...
Garland         0
Garfield        0
Galveston       0
Gallia          0
Ziebach         0
Name: count, Length: 1871, dtype: int64

west des moines
County
McHenry       685
Mchenry       149
Abbeville       0
Otter Tail      0
Page            0
             ...
Garland         0
Garfield        0
Galveston       0
Gallia          0
Ziebach         0
Name: count, Length: 1871, dtype: int64

west des moines
County
McIntosh      302
Mcintosh        3
Abbeville       0
Otter Tail      0
Page            0
             ...
Garland         0
Garfield        0
Galveston       0
Gallia          0
Ziebach         0
Name: count, Length: 1871, dtype: int64

west des moines
County
McKean        1591
Mckean          17
Otter Tail       0
Page             0
Pacific          0
              ...
Garland          0
Garfield         0
Galveston        0
Gallia           0
Ziebach          0
Name: count, Length: 1871, dtype: int64

west des moines
County
McLean       402
Mclean         1
Ouachita       0
Page           0
Pacific        0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
McLennan     485
Mclennan      30
Abbeville      0
Ouachita       0
Page           0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
McLeod       943
Mcleod         7
Abbeville      0
Ouachita       0
Page           0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
McMinn       671
Mcminn         1
Abbeville      0
Ouachita       0
Page           0
            ...
Garland        0
Garfield       0
Galveston      0
Gallia         0
Ziebach        0
Name: count, Length: 1871, dtype: int64

west des moines
County
St John the Baptist    117
St John The Baptist      2
Abbeville                0
Ottawa                   0
Ozaukee                  0
                      ...
Garland                  0
Garfield                 0
Galveston                0
Gallia                   0
Ziebach                  0
Name: count, Length: 1871, dtype: int64

In [65]:
county_corrections = {}

for normalized, variants in county_variants.items():
    counts = (
        car_accidents.loc[
            county_normalized.eq(normalized),
            'County'
        ]
        .value_counts()
    )
    
    canonical = counts.index[0]
    
    for variant in variants:
        if variant != canonical:
            county_corrections[variant] = canonical

In [66]:
for original, corrected in county_corrections.items():
    print(f"{original} → {corrected}")

Dekalb → DeKalb
Desoto → DeSoto
Dewitt → DeWitt
District Of Columbia → District of Columbia
Dupage → DuPage
Fond Du Lac → Fond du Lac
Isle Of Wight → Isle of Wight
King And Queen → King and Queen
Lagrange → LaGrange
Laporte → LaPorte
Lewis And Clark → Lewis and Clark
Mcclain → McClain
Mccormick → McCormick
Mccracken → McCracken
Mcdowell → McDowell
Mcduffie → McDuffie
Mchenry → McHenry
Mcintosh → McIntosh
Mckean → McKean
Mclean → McLean
Mclennan → McLennan
Mcleod → McLeod
Mcminn → McMinn
St John The Baptist → St John the Baptist

In [67]:
car_accidents['County'] = car_accidents['County'].astype('string')
car_accidents['County'] = car_accidents['County'].replace(county_corrections)

comprobar

In [68]:
county_normalized = (
    car_accidents['County']
    .str.strip()
    .str.casefold()
)

In [69]:
city_check = (
    pd.DataFrame({
        'original': car_accidents['City'],
        'normalized': city_normalized
    })
    .dropna()
    .groupby('normalized')['original']
    .nunique()
)

city_check[city_check > 1]

Series([], Name: original, dtype: int64)

Revisar columna state

In [70]:
state_normalized = (
    car_accidents['State']
    .dropna()
    .str.strip()
    .str.lower()
)

In [71]:
state_variants = (
    pd.DataFrame({
        'original': car_accidents.loc[city_normalized.index, 'State'],
        'normalized': state_normalized
    })
    .groupby('normalized')['original']
    .nunique()
    .sort_values(ascending=False)
)

state_variants[state_variants > 1]

Series([], Name: original, dtype: int64)

Revisar columna Timezone

In [72]:
car_accidents['Timezone'].unique()

['US/Eastern', 'US/Pacific', NaN, 'US/Central', 'US/Mountain']
Categories (4, object): ['US/Central', 'US/Eastern', 'US/Mountain', 'US/Pacific']

In [73]:
weather_normalized = (
    car_accidents['Weather_Condition']
    .dropna()
    .str.strip()
    .str.lower()
)

In [74]:
weather_variants = (
    pd.DataFrame({
        'original': car_accidents.loc[weather_normalized.index, 'Weather_Condition'],
        'normalized': weather_normalized
    })
    .groupby('normalized')['original']
    .nunique()
    .sort_values(ascending=False)
)

In [75]:
weather_variants[weather_variants > 1]

Series([], Name: original, dtype: int64)

### Revisar outliers

In [76]:
 car_accidents.describe()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,7.728394e+06,6985228,6985228,7.728394e+06,7.728394e+06,4.325632e+06,4.325632e+06,7.728394e+06,7608166,7.564541e+06,5.729375e+06,7.554250e+06,7.587715e+06,7.551296e+06,7.157161e+06,5.524808e+06
mean,2.212384e+00,2020-03-21 21:49:59.056443136,2020-03-22 04:56:51.646936064,3.620119e+01,-9.470255e+01,3.626183e+01,-9.572557e+01,5.618423e-01,2020-06-02 10:06:41.888674560,6.166329e+01,5.825105e+01,6.483104e+01,2.953899e+01,9.090376e+00,7.685490e+00,8.407210e-03
min,1.000000e+00,2016-01-14 20:18:33,2016-02-08 06:37:08,2.455480e+01,-1.246238e+02,2.456601e+01,-1.245457e+02,0.000000e+00,2016-01-14 19:51:00,-8.900000e+01,-8.900000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.000000e+00,2018-09-17 02:20:31.750000128,2018-09-17 05:23:37.500000,3.339963e+01,-1.172194e+02,3.346207e+01,-1.177543e+02,0.000000e+00,2018-11-20 18:35:00,4.900000e+01,4.300000e+01,4.800000e+01,2.937000e+01,1.000000e+01,4.600000e+00,0.000000e+00
50%,2.000000e+00,2020-06-23 13:37:23.500000,2020-06-23 15:20:42,3.582397e+01,-8.776662e+01,3.618349e+01,-8.802789e+01,3.000000e-02,2020-11-10 13:53:00,6.400000e+01,6.200000e+01,6.700000e+01,2.986000e+01,1.000000e+01,7.000000e+00,0.000000e+00
75%,2.000000e+00,2021-10-28 15:44:07,2021-10-29 14:57:46.500000,4.008496e+01,-8.035368e+01,4.017892e+01,-8.024709e+01,4.640000e-01,2022-01-19 14:27:00,7.600000e+01,7.500000e+01,8.400000e+01,3.003000e+01,1.000000e+01,1.040000e+01,0.000000e+00
max,4.000000e+00,2023-03-31 23:30:00,2023-03-31 23:59:00,4.900220e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,4.417500e+02,2023-03-31 23:53:00,2.070000e+02,2.070000e+02,1.000000e+02,5.863000e+01,1.400000e+02,1.087000e+03,3.647000e+01
std,4.875313e-01,NaN,NaN,5.076079e+00,1.739176e+01,5.272905e+00,1.810793e+01,1.776811e+00,NaN,1.901365e+01,2.238983e+01,2.282097e+01,1.006190e+00,2.688316e+00,5.424983e+00,1.102246e-01

In [77]:
 car_accidents['Temperature(F)'].describe()

count    7.564541e+06
mean     6.166329e+01
std      1.901365e+01
min     -8.900000e+01
25%      4.900000e+01
50%      6.400000e+01
75%      7.600000e+01
max      2.070000e+02
Name: Temperature(F), dtype: float64

In [78]:
Q1 = car_accidents['Temperature(F)'].quantile(0.25)
Q3 = car_accidents['Temperature(F)'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Límite inferior:", lower_limit)
print("Límite superior:", upper_limit)

Límite inferior: 8.5
Límite superior: 116.5

In [79]:
outliers_temp = car_accidents[
    (car_accidents['Temperature(F)'] < lower_limit) |
    (car_accidents['Temperature(F)'] > upper_limit)
]

print("Outliers:", len(outliers_temp))

Outliers: 50515

In [80]:
car_accidents['Temperature(F)'].nsmallest(20)

1535734   -89.0
1535736   -89.0
1535738   -89.0
1535740   -89.0
1535741   -89.0
1535743   -89.0
1535744   -89.0
1535745   -89.0
7104502   -89.0
7104508   -89.0
200806    -77.8
200834    -77.8
201309    -77.8
201311    -77.8
2699464   -77.8
2699467   -77.8
2699474   -77.8
2998211   -77.8
3112133   -77.8
3112138   -77.8
Name: Temperature(F), dtype: float64

In [81]:
car_accidents['Temperature(F)'].nlargest(20)

4208142    207.0
4546366    207.0
5029338    207.0
1380565    203.0
928934     196.0
929003     196.0
5600272    196.0
5848377    196.0
6011434    196.0
1278506    189.0
1380133    174.0
1380135    174.0
4372832    172.0
5034277    172.0
7383835    170.6
7504006    168.8
504587     167.0
4205310    162.0
4712821    162.0
292016     161.6
Name: Temperature(F), dtype: float64

In [82]:
 car_accidents['Wind_Speed(mph)'].describe().round(2)

count    7157161.00
mean           7.69
std            5.42
min            0.00
25%            4.60
50%            7.00
75%           10.40
max         1087.00
Name: Wind_Speed(mph), dtype: float64

In [83]:
 car_accidents['Wind_Chill(F)'].describe().round(2)

count    5729375.00
mean          58.25
std           22.39
min          -89.00
25%           43.00
50%           62.00
75%           75.00
max          207.00
Name: Wind_Chill(F), dtype: float64

In [84]:
car_accidents['Wind_Chill(F)'].nsmallest(20)

1535734   -89.0
1535736   -89.0
1535738   -89.0
1535740   -89.0
1535741   -89.0
1535743   -89.0
1535744   -89.0
1535745   -89.0
7104502   -89.0
7104508   -89.0
6825220   -80.0
4891714   -69.0
7527169   -65.9
3753804   -63.0
3814186   -63.0
4169914   -63.0
4262321   -63.0
4304949   -63.0
4474490   -63.0
4814341   -63.0
Name: Wind_Chill(F), dtype: float64

In [85]:
car_accidents['Humidity(%)'].describe().round(2)

count    7554250.00
mean          64.83
std           22.82
min            1.00
25%           48.00
50%           67.00
75%           84.00
max          100.00
Name: Humidity(%), dtype: float64

In [86]:
car_accidents['Pressure(in)'].describe().round(2)

count    7587715.00
mean          29.54
std            1.01
min            0.00
25%           29.37
50%           29.86
75%           30.03
max           58.63
Name: Pressure(in), dtype: float64

In [87]:
car_accidents['Visibility(mi)'].describe().round(2)

count    7551296.00
mean           9.09
std            2.69
min            0.00
25%           10.00
50%           10.00
75%           10.00
max          140.00
Name: Visibility(mi), dtype: float64

In [88]:
car_accidents['Precipitation(in)'].describe().round(2)

count    5524808.00
mean           0.01
std            0.11
min            0.00
25%            0.00
50%            0.00
75%            0.00
max           36.47
Name: Precipitation(in), dtype: float64

In [118]:
car_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 47 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   category
 13  County                 string
 14  State                  category
 15  Zipcode                object
 16  Timezone               category
 17  Airport_Code           category
 18  Weather_Timestamp      datetime64[ns]
 19  Temperature(F)         float64
 20  Wind_Chill(F)          float64
 21  Humidity(%)            float64
 22  Pressure(in)           float64
 23  Visibility(mi)         float64
 24  Wind_Direction         category
 25  Wind_Speed(mph)        float64
 26  Precipitation(in)      float64
 27  Weather_Condition      object
 28  Amenity                bool
 29  Bump                   bool
 30  Crossing               bool
 31  Give_Way               bool
 32  Junction               bool
 33  No_Exit                bool
 34  Railway                bool
 35  Roundabout             bool
 36  Station                bool
 37  Stop                   bool
 38  Traffic_Calming        bool
 39  Traffic_Signal         bool
 40  Turning_Loop           bool
 41  Sunrise_Sunset         category
 42  Civil_Twilight         category
 43  Nautical_Twilight      category
 44  Astronomical_Twilight  category
 45  lat_diff               float64
 46  lng_diff               float64
dtypes: bool(13), category(9), datetime64[ns](3), float64(14), int64(1), object(6), string(1)
memory usage: 1.6+ GB

# Análisis Exploratorio de Datos

## Análisis temporal

que años hay mas accidentes

In [89]:
accidents_temporal = car_accidents[['Start_Time', 'End_Time']].copy()

accidents_temporal['Year'] = accidents_temporal['Start_Time'].dt.year

In [90]:
accidents_temporal.groupby('Year').size().sort_values(ascending=False)

Year
2021.0    1412433
2022.0    1268806
2020.0    1161598
2019.0     954302
2018.0     893426
2017.0     717290
2016.0     410821
2023.0     166552
dtype: int64

que meses hay mas accidentes

In [91]:
meses = { 1: 'Enero', 2: 'Febrero', 3: 'Marzo', 4: 'Abril', 5: 'Mayo', 6: 'Junio', 7: 'Julio', 8: 'Agosto', 9: 'Septiembre', 10: 'Octubre', 11: 'Noviembre',
    12: 'Diciembre'}

accidents_temporal['Month'] = accidents_temporal['Start_Time'].dt.month.map(meses)

accidents_temporal.groupby('Month').size().sort_values(ascending = False)

Month
Diciembre     758783
Noviembre     695612
Enero         652682
Octubre       630325
Septiembre    593815
Febrero       585606
Agosto        547206
Abril         526210
Junio         524750
Mayo          505614
Marzo         501362
Julio         463263
dtype: int64

los ultimos meses del años y los primeros son los que mas accidentes hay

Cuales son los dias de la semana que mas accidentes hay

In [92]:
dias_semana = {0: 'Lunes', 1: 'Martes', 2: 'Miércoles', 3: 'Jueves', 4: 'Viernes', 5: 'Sábado',
    6: 'Domingo'}

accidents_temporal['Week_day'] = accidents_temporal['Start_Time'].dt.day_of_week.map(dias_semana)

In [93]:
accidents_temporal.groupby('Week_day').size().sort_values(ascending = False)

Week_day
Viernes      1237229
Jueves       1196137
Miércoles    1195864
Martes       1177923
Lunes        1108807
Sábado        579153
Domingo       490115
dtype: int64

Comparacion de accidentes en fin de semana contra entre semana

In [94]:
accidents_temporal['Weekend'] = accidents_temporal['Start_Time'].dt.dayofweek >= 5

In [95]:
accidents_temporal.groupby('Weekend').size().sort_values(ascending = False)

Weekend
False    6659126
True     1069268
dtype: int64

los fines de semana hay menos accidentes qeu entre semana

Que horas hay mas accidentes

In [96]:
horas_dia = { 0: '12 AM', 1: '1 AM', 2: '2 AM', 3: '3 AM', 4: '4 AM', 5: '5 AM', 6: '6 AM', 7: '7 AM', 8: '8 AM', 9: '9 AM',
    10: '10 AM', 11: '11 AM',12: '12 PM',13: '1 PM',14: '2 PM',15: '3 PM',16: '4 PM',17: '5 PM',18: '6 PM',19: '7 PM',20: '8 PM',
    21: '9 PM',22: '10 PM',23: '11 PM'}

accidents_temporal['Hour'] = accidents_temporal['Start_Time'].dt.hour.map(horas_dia)

In [97]:
accidents_temporal.groupby('Hour').size().sort_values(ascending = False)

Hour
7 AM     546789
8 AM     541643
4 PM     520177
5 PM     516626
3 PM     463389
2 PM     394697
6 PM     390621
6 AM     375179
1 PM     352361
9 AM     334067
11 AM    322215
12 PM    316904
10 AM    313625
7 PM     267045
5 AM     209579
8 PM     201883
9 PM     169500
4 AM     149077
10 PM    148605
11 PM    110428
12 AM     98452
1 AM      85743
2 AM      82394
3 AM      74229
dtype: int64

In [98]:
accidents_temporal.groupby('Hour').size().div(len(car_accidents)).mul(100).sort_values(ascending = False).round(2)

Hour
7 AM     7.08
8 AM     7.01
4 PM     6.73
5 PM     6.68
3 PM     6.00
2 PM     5.11
6 PM     5.05
6 AM     4.85
1 PM     4.56
9 AM     4.32
11 AM    4.17
12 PM    4.10
10 AM    4.06
7 PM     3.46
5 AM     2.71
8 PM     2.61
9 PM     2.19
4 AM     1.93
10 PM    1.92
11 PM    1.43
12 AM    1.27
1 AM     1.11
2 AM     1.07
3 AM     0.96
dtype: float64

Se observa que en la mañana cuando la gente habitualmente va al trabajo y a la escuela y cuando salen de regreso a su casa es las horas donde mas accidentes hay

# Analisis de Severidad

cantidad de accidentes por serevidad

In [99]:
accidents_severity = car_accidents.copy()

accidents_severity.groupby('Severity').size().sort_values(ascending=False)

Severity
2    6156981
3    1299337
4     204710
1      67366
dtype: int64

Horas donde hay mas accidentes severos

In [100]:
horas_dia = { 0: '12 AM', 1: '1 AM', 2: '2 AM', 3: '3 AM', 4: '4 AM', 5: '5 AM', 6: '6 AM', 7: '7 AM', 8: '8 AM', 9: '9 AM',
    10: '10 AM', 11: '11 AM',12: '12 PM',13: '1 PM',14: '2 PM',15: '3 PM',16: '4 PM',17: '5 PM',18: '6 PM',19: '7 PM',20: '8 PM',
    21: '9 PM',22: '10 PM',23: '11 PM'}

accidents_severity['Hour'] = accidents_severity['Start_Time'].dt.hour.map(horas_dia)

accidents_severe = accidents_severity[accidents_severity['Severity'] == 4]

accidents_severe.groupby('Hour').size().sort_values(ascending = False)

Hour
4 PM     10573
5 PM     10328
3 PM     10315
6 PM      9610
2 PM      9557
1 PM      9062
7 AM      9041
8 AM      9014
12 PM     8516
9 AM      8301
7 PM      8028
10 AM     7926
6 AM      7904
11 AM     7801
8 PM      7339
9 PM      6902
5 AM      6708
12 AM     6588
10 PM     6483
11 PM     6003
4 AM      5363
3 AM      4499
2 AM      4492
1 AM      4376
dtype: int64

los accidente mas severos se concentran mas a la hora de vuelta a la casa que en la mañana

dias donde hay mas accidentes severos

In [101]:
dias_semana = {0: 'Lunes', 1: 'Martes', 2: 'Miércoles', 3: 'Jueves', 4: 'Viernes', 5: 'Sábado',
    6: 'Domingo'}

accidents_severity['Week_day'] = accidents_severity['Start_Time'].dt.day_of_week.map(dias_semana)

accidents_severe = accidents_severity[accidents_severity['Severity'] == 4]

accidents_severe.groupby('Week_day').size().sort_values(ascending = False)

Week_day
Viernes      29863
Jueves       28751
Martes       28741
Miércoles    28704
Lunes        28135
Sábado       20803
Domingo      19732
dtype: int64

In [102]:
accidents_severe.groupby('Week_day').size().div(len(car_accidents)).mul(100).sort_values(ascending = False)

Week_day
Viernes      0.386406
Jueves       0.372018
Martes       0.371888
Miércoles    0.371410
Lunes        0.364047
Sábado       0.269176
Domingo      0.255318
dtype: float64

severidad

In [103]:
pd.crosstab(
    accidents_severity['Traffic_Signal'],
    accidents_severity['Severity'],
    normalize='index'
) * 100

Severity               1          2          3         4
Traffic_Signal
False           0.623043  78.186857  18.387206  2.802894
True            2.302994  88.188205   7.747086  1.761715

### Analisis Climatico

accidentes por severdad segun el clima promedio

In [104]:
weather_by_severity = ( accidents_severity.groupby('Severity')[[
        'Temperature(F)',
        'Wind_Chill(F)',
        'Humidity(%)',
        'Pressure(in)',
        'Visibility(mi)',
        'Wind_Speed(mph)',
        'Precipitation(in)'
    ]]
    .mean()
)

weather_by_severity

,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
Severity,,,,,,,
1,72.417672,72.241676,61.907452,29.206988,9.475379,7.142302,0.005067
2,61.547184,58.576986,64.665645,29.515856,9.086604,7.566564,0.007228
3,62.201117,55.725601,65.381389,29.686656,9.092717,8.317192,0.017267
4,58.141514,53.342730,67.301981,29.405001,9.060768,7.656266,0.007488

condicion climatica en los accidentes

In [105]:
accidents_severity['Weather_Condition'].value_counts().head(20)

Weather_Condition
Fair                       2560802
Mostly Cloudy              1016195
Cloudy                      817082
Clear                       808743
Partly Cloudy               698972
Overcast                    382866
Light Rain                  352957
Scattered Clouds            204829
Light Snow                  128680
Fog                          99238
Rain                         84331
Haze                         76223
Fair / Windy                 35671
Heavy Rain                   32309
Light Drizzle                22684
Thunder in the Vicinity      17611
Cloudy / Windy               17035
T-Storm                      16810
Mostly Cloudy / Windy        16508
Snow                         15537
Name: count, dtype: int64

In [106]:
top_weather = accidents_severity['Weather_Condition'].value_counts().head(10).index

weather_severity = pd.crosstab(
    accidents_severity.loc[
        accidents_severity['Weather_Condition'].isin(top_weather),
        'Weather_Condition'
    ],
    accidents_severity.loc[
        accidents_severity['Weather_Condition'].isin(top_weather),
        'Severity'
    ]
).reindex(top_weather)

weather_severity

Severity               1        2       3      4
Weather_Condition
Fair               34359  2226576  240084  59783
Mostly Cloudy      10676   792735  189229  23555
Cloudy              7985   692929   93340  22828
Clear                337   536971  244956  26479
Partly Cloudy       6820   548760  127692  15700
Overcast             115   248938  119946  13867
Light Rain          2338   270162   71097   9360
Scattered Clouds      73   132748   66037   5971
Light Snow            86   101703   22132   4759
Fog                  662    86212    9590   2774

no parece aver relacion en si hay mas accidentes con clima violento ni con la severedad

### Analisis Geografíco

estados con mas accidentes

In [107]:
state_summary = (
    car_accidents.groupby('State')
    .size()
    .reset_index(name='Accidents')
)

state_summary['Percentage'] = (
    state_summary['Accidents']
    .div(state_summary['Accidents'].sum())
    .mul(100)
    .round(2)
)

state_summary = state_summary.sort_values(
    'Accidents',
    ascending=False
)

state_summary.head(20)

C:\Users\ricks\AppData\Local\Temp\ipykernel_20064\3409022428.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  car_accidents.groupby('State')

   State  Accidents  Percentage
3     CA    1741433       22.53
8     FL     880192       11.39
41    TX     582837        7.54
38    SC     382557        4.95
32    NY     347960        4.50
25    NC     338199        4.38
43    VA     303301        3.92
36    PA     296620        3.84
21    MN     192084        2.49
35    OR     179660        2.32
2     AZ     170609        2.21
9     GA     169234        2.19
12    IL     168958        2.19
40    TN     167388        2.17
20    MI     162191        2.10
16    LA     149701        1.94
29    NJ     140719        1.82
18    MD     140417        1.82
33    OH     118115        1.53
45    WA     108221        1.40

ciudades con mas accidentes

In [108]:
city_summary = (
    car_accidents.groupby('City')
    .size()
    .reset_index(name='Accidents')
)

city_summary['Percentage'] = (
    city_summary['Accidents']
    .div(city_summary['Accidents'].sum())
    .mul(100)
    .round(2)
)

city_summary = city_summary.sort_values(
    'Accidents',
    ascending=False
)

city_summary.head(20)

C:\Users\ricks\AppData\Local\Temp\ipykernel_20064\4128863649.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  car_accidents.groupby('City')

                City  Accidents  Percentage
7624           Miami     186917        2.42
5545         Houston     169609        2.19
6868     Los Angeles     156491        2.02
2020       Charlotte     138652        1.79
2818          Dallas     130939        1.69
9023         Orlando     109733        1.42
476           Austin      97359        1.26
9955         Raleigh      86079        1.11
8237       Nashville      72930        0.94
653      Baton Rouge      71588        0.93
443          Atlanta      68186        0.88
10571     Sacramento      66264        0.86
10712      San Diego      55504        0.72
9470         Phoenix      53974        0.70
7763     Minneapolis      51488        0.67
10184       Richmond      48845        0.63
8886   Oklahoma City      46092        0.60
5811    Jacksonville      42447        0.55
12330         Tucson      39304        0.51
2412        Columbia      38178        0.49

Condados con mas accidentes

In [109]:
county_summary = (
    car_accidents.groupby('County')
    .size()
    .reset_index(name='Accidents')
)

county_summary['Percentage'] = (
    county_summary['Accidents']
    .div(county_summary['Accidents'].sum())
    .mul(100)
    .round(2)
)

county_summary = county_summary.sort_values(
    'Accidents',
    ascending=False
)

county_summary.head(20)

                County  Accidents  Percentage
962        Los Angeles     526851        6.82
1070        Miami-Dade     251601        3.26
1209            Orange     241275        3.12
722             Harris     181196        2.34
434             Dallas     157024        2.03
1052       Mecklenburg     147265        1.91
1101        Montgomery     136788        1.77
1731              Wake     117890        1.53
1447    San Bernardino     109631        1.42
1669            Travis     107881        1.40
1006          Maricopa     106737        1.38
1448         San Diego     104165        1.35
11             Alameda      98553        1.28
444           Davidson      96580        1.25
1420        Sacramento      95377        1.23
1387         Riverside      88248        1.14
514   East Baton Rouge      75260        0.97
1465       Santa Clara      70482        0.91
385               Cook      65599        0.85
1010            Marion      59498        0.77

zipcodes con mas accidentes

In [110]:
zipcode_summary = (
    car_accidents
    .groupby(['State', 'Zipcode'], observed=True)
    .size()
    .reset_index(name='Accidents')
    .sort_values('Accidents', ascending=False)
)

zipcode_summary.head(20)

       State Zipcode  Accidents
59593     CA   91761      11247
56093     CA   91706      10022
72261     CA   92407       8922
73450     CA   92507       8850
228045    FL   33186       8375
207262    FL   32819       7461
59990     CA   91765       7377
223947    FL   33169       7106
34959     CA   90023       7066
69533     CA   92324       7010
713139    TX   75243       6914
32724     CA   90012       6852
49507     CA   90805       6703
48368     CA   90703       6627
53089     CA   91342       6471
42558     CA   90248       6411
66171     CA   92108       6382
54786     CA   91403       6361
109639    CA   94551       6250
617229    SC   29210       6245

In [111]:
zipcode_summary = (
    car_accidents
    .groupby('Zipcode', observed=True)
    .size()
    .reset_index(name='Accidents')
    .sort_values('Accidents', ascending=False)
)

zipcode_summary.head(20)

       Zipcode  Accidents
698133   91761      11247
694633   91706      10022
710801   92407       8922
711990   92507       8850
362775   33186       8375
341992   32819       7461
698530   91765       7377
358677   33169       7106
673499   90023       7066
708073   92324       7010
583956   75243       6914
671264   90012       6852
688047   90805       6703
686908   90703       6627
691629   91342       6471
681098   90248       6411
704711   92108       6382
693326   91403       6361
748179   94551       6250
234938   29210       6245

Cuanto cambio el coche de posicion en el accidente (ver nans)

In [112]:
same_location = (
    (car_accidents['Start_Lat'] == car_accidents['End_Lat']) &
    (car_accidents['Start_Lng'] == car_accidents['End_Lng'])
)

same_location.sum()

np.int64(397798)

In [113]:
car_accidents['lat_diff'] = (
    car_accidents['End_Lat'] - car_accidents['Start_Lat']
).abs()

car_accidents['lng_diff'] = (
    car_accidents['End_Lng'] - car_accidents['Start_Lng']
).abs()

In [114]:
car_accidents[['lat_diff', 'lng_diff']].describe()

           lat_diff      lng_diff
count  4.325632e+06  4.325632e+06
mean   7.286940e-03  9.677582e-03
std    1.777017e-02  2.675385e-02
min    0.000000e+00  0.000000e+00
25%    2.660000e-04  3.400000e-04
50%    1.752000e-03  2.170000e-03
75%    7.235000e-03  9.146000e-03
max    2.223140e+00  2.798300e+00

In [115]:
car_accidents.groupby('Severity')[['lat_diff', 'lng_diff']].mean()

          lat_diff  lng_diff
Severity
1         0.001799  0.002169
2         0.007243  0.009578
3         0.005386  0.006801
4         0.010633  0.015291

### Analisis de infraestructura

In [116]:
infrastructure_cols = [
    'Amenity',
    'Bump',
    'Crossing',
    'Give_Way',
    'Junction',
    'No_Exit',
    'Railway',
    'Roundabout',
    'Station',
    'Stop',
    'Traffic_Calming',
    'Traffic_Signal',
    'Turning_Loop'
]

infrastructure_summary = accidents_severity[infrastructure_cols].sum().to_frame(name='Yes')

infrastructure_summary['No'] = (
    accidents_severity[infrastructure_cols].notna().sum()
    - infrastructure_summary['Yes']
)

infrastructure_summary

                     Yes       No
Amenity            96334  7632060
Bump                3514  7724880
Crossing          873763  6854631
Give_Way           36582  7691812
Junction          571342  7157052
No_Exit            19545  7708849
Railway            66979  7661415
Roundabout           249  7728145
Station           201901  7526493
Stop              214371  7514023
Traffic_Calming     7598  7720796
Traffic_Signal   1143772  6584622
Turning_Loop           0  7728394

In [117]:
infrastructure_severity = pd.DataFrame()

for col in infrastructure_cols:
    table = pd.crosstab(
        accidents_severity[col],
        accidents_severity['Severity']
    )
    
    infrastructure_severity[col] = table.stack()

infrastructure_severity

                  Amenity     Bump  Crossing  Give_Way  Junction  No_Exit  \
Amenity Severity
False   1           65987    67332     48675     66817     64239    66985
        2         6068089  6153837   5363435   6126858   5741842  6140021
        3         1295307  1299031   1251305   1294598   1166841  1297502
        4          202677   204680    191216    203539    184130   204341
True    1            1379       34     18691       549      3127      381
        2           88892     3144    793546     30123    415139    16960
        3            4030      306     48032      4739    132496     1835
        4            2033       30     13494      1171     20580      369

                  Railway  Roundabout  Station     Stop  Traffic_Calming  \
Amenity Severity
False   1           66302       67366    64658    64723            67280
        2         6101200     6156743  5972944  5958591          6150420
        3         1290760     1299332  1286949  1291686          1298485
        4          203153      204704   201942   199023           204611
True    1            1064           0     2708     2643               86
        2           55781         238   184037   198390             6561
        3            8577           5    12388     7651              852
        4            1557           6     2768     5687               99

                  Traffic_Signal  Turning_Loop
Amenity Severity
False   1                  41025       67366.0
        2                5148309     6156981.0
        3                1210728     1299337.0
        4                 184560      204710.0
True    1                  26341           NaN
        2                1008672           NaN
        3                  88609           NaN
        4                  20150           NaN

Guardar el archivo

In [119]:
car_accidents.to_parquet(
    'US_Accidents_clean.parquet',
    index=False
)